# Generated by Django 3.2.3 on 2021-05-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ola_cab', '0002_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
